import { useAdCampaign } from '../context/AdCampaignContext';
import { getCTAs, ctaLabels } from '../data/platformOptions';
import { Input, Select, Textarea, Section, ErrorList, StepActions } from './FormControls';
import MediaInput from './MediaInput';
import useStepValidation from '../lib/useStepValidation';
export default function AdCreativeStep() {
  const { campaignData: data, updateField: update, nextStep, prevStep } = useAdCampaign();
  const { errors, errorFor, advance, focusError } = useStepValidation(data,2,nextStep);
  const props = { data, update };
  const updateCard = (index, fields) => update('carouselCards',data.carouselCards.map((card,i) => i === index ? {...card,...fields} : card));
  return <div className="step-content"><div className="step-heading"><span className="eyebrow">Ad level</span><h2>Build your ad</h2><p>Configure the identity, creative, and destination. Inspect each selected placement.</p></div><ErrorList errors={errors} onSelect={focusError}/>
    <Section title="Ad details and identity" help="identity"><Input {...props} name="adName" label="Ad name" placeholder="Offer_Creative_V1" error={errorFor('adName')}/><div className="field-grid"><Input {...props} name="facebookPage" label="Facebook Page" error={errorFor('facebookPage')} hint="Enter a Page name. No account connection is made."/><Input {...props} name="instagramAccount" label="Instagram account" optional placeholder="@yourbusiness"/></div></Section>
    <Section title="Ad creative" help="creativeFormat"><Select {...props} name="adFormat" label="Format" options={[{value:'single-image',label:'Single image'},{value:'carousel',label:'Carousel'}]}/>
      {data.adFormat === 'single-image' ? <MediaInput value={data.imageUrl} name={data.imageName} alt={data.imageAlt} error={errorFor('imageUrl')} onChange={fields => Object.entries(fields).forEach(([key,value]) => update(key,value))}/> : <div id="carouselCards" tabIndex={-1} className="carousel-editor">{data.carouselCards.map((card,index) => <div className="carousel-card-editor" key={card.id}><div className="section-heading"><h4>Card {index+1}</h4><div className="card-actions"><button type="button" className="text-button" disabled={index === 0} onClick={() => { const cards = [...data.carouselCards]; [cards[index-1],cards[index]] = [cards[index],cards[index-1]]; update('carouselCards',cards); }}>Move up</button><button type="button" className="text-button" onClick={() => update('carouselCards',data.carouselCards.filter((_,i) => i !== index))}>Remove card {index+1}</button></div></div><MediaInput id={`card-${index}-image`} value={card.imageUrl} name={card.imageName} alt={card.imageAlt} onChange={fields => updateCard(index,fields)}/><div className="field"><label htmlFor={`card-${index}-headline`}>Card headline</label><input id={`card-${index}-headline`} maxLength={24000} value={card.headline} onChange={e => updateCard(index,{headline:e.target.value})}/></div>{data.destination === 'website' && <div className="field"><label htmlFor={`card-${index}-url`}>Card website URL <span className="optional">(optional override)</span></label><input id={`card-${index}-url`} type="url" maxLength={24000} value={card.websiteUrl} onChange={e => updateCard(index,{websiteUrl:e.target.value})} placeholder="Uses the main website URL when blank"/></div>}</div>)}<button type="button" className="button secondary" disabled={data.carouselCards.length >= 10} onClick={() => update('carouselCards',[...data.carouselCards,{id:crypto.randomUUID(),imageUrl:'',imageName:'',imageAlt:'',headline:'',websiteUrl:''}])}>Add carousel card</button><p className="field-hint">Add 2–10 cards. Preview and record the order.</p>{errorFor('carouselCards') && <p className="field-error">{errorFor('carouselCards')}</p>}</div>}
      <Textarea {...props} name="primaryText" label="Primary text" help="primaryText" error={errorFor('primaryText')} hint={`${data.primaryText.length} characters. Preview truncation varies by placement.`} rows={4}/>
      <Input {...props} name="headline" label="Headline" help="headline" optional={data.destination !== 'website' || data.adFormat === 'carousel'} error={errorFor('headline')}/><Input {...props} name="description" label="Description" help="headline" optional/>
      <Select {...props} name="callToAction" label="Call to action" help="callToAction" options={getCTAs(data.destination).map(value => ({value,label:ctaLabels[value]}))} error={errorFor('callToAction')}/>
    </Section>
    {data.destination === 'website' && <Section title="Website destination" help="websiteUrl"><Input {...props} name="websiteUrl" label="Website URL" type="url" error={errorFor('websiteUrl')} placeholder="https://example.com/offer"/><Input {...props} name="urlParameters" label="URL parameters" optional placeholder="utm_source=facebook&utm_medium=paid_social&utm_campaign=launch" hint="Parameters are recorded and appended locally. No tracking connection is made."/></Section>}
    {data.destination === 'instant-form' && <Section title="Instant form" help="instantForm"><Input {...props} name="formName" label="Form name" error={errorFor('formName')}/><Input {...props} name="formHeadline" label="Form headline" error={errorFor('formHeadline')}/><Textarea {...props} name="formDescription" label="Form introduction" optional/><fieldset id="formQuestions" className="placement-options" tabIndex={-1}><legend>Questions to request</legend>{['Full name','Email','Phone number','City','Preferred contact method'].map(question => <label key={question}><input type="checkbox" checked={data.formQuestions.includes(question)} onChange={e => update('formQuestions',e.target.checked ? [...data.formQuestions,question] : data.formQuestions.filter(q => q !== question))}/>{question}</label>)}</fieldset>{errorFor('formQuestions') && <p className="field-error">{errorFor('formQuestions')}</p>}<Input {...props} name="privacyUrl" label="Privacy-policy URL" type="url" error={errorFor('privacyUrl')}/><Textarea {...props} name="thankYouMessage" label="Completion message" optional/><p className="field-hint">Preview only. No lead information is collected.</p></Section>}
    {data.destination === 'messages' && <Section title="Messaging destination" help="messages"><Select {...props} name="messageApp" label="Messaging app" options={['Messenger','Instagram']}/><Textarea {...props} name="messageGreeting" label="Opening message" error={errorFor('messageGreeting')} placeholder="Write the greeting someone would see when starting a conversation."/></Section>}
    {data.destination === 'app' && <Section title="App destination" help="app"><Input {...props} name="appName" label="App name" error={errorFor('appName')}/><Select {...props} name="appStore" label="App store" options={['Apple App Store','Google Play','Meta Horizon Store']}/><Input {...props} name="appUrl" label="App store URL" type="url" error={errorFor('appUrl')}/></Section>}
    <StepActions back={prevStep} next={advance} label="Next: Review & publish"/>
  </div>;
}
