import { Layers, Target, Users, Image, ClipboardList, BookOpen } from 'lucide-react';
import { useAdCampaign } from '../context/AdCampaignContext';
import ProgressBar from './ProgressBar';
import WorkspaceToolbar from './WorkspaceToolbar';
import InfoIcon from './InfoIcon';
const icons = [Target,Users,Image,ClipboardList];
export default function MainLayout({ leftPanel, rightPanel }) {
  const { campaignData, currentStep, goToStep, storageError, workspace, hasUnpublishedChanges } = useAdCampaign();
  const labels = [campaignData.campaignName || 'New campaign',campaignData.adSetName || 'New ad set',campaignData.adName || 'New ad','Review & publish'];
  return <div className="workspace-screen"><a className="skip-link" href="#step-main">Skip to campaign settings</a><header className="app-header"><div className="app-brand"><div className="brand-mark"><Layers size={23}/></div><div><h1>Ads Manager <span>practice</span></h1><p>MARK 4360 · Facebook Simulator Revamp</p></div></div><div className="account-badge"><BookOpen size={17}/><span>Classroom account · USD</span></div></header>
    <div className="app-shell"><aside className="campaign-tree" aria-label="Campaign hierarchy"><div className="tree-heading"><span>Campaign structure</span><InfoIcon contentKey="hierarchy"/></div>{labels.map((label,index) => { const Icon=icons[index]; return <button type="button" key={index} className={`${currentStep === index ? 'active' : ''} tree-level-${index}`} onClick={() => goToStep(index)} aria-current={currentStep === index ? 'step' : undefined}><Icon size={17}/><span><small>{['Campaign','Ad set','Ad','Final review'][index]}</small><strong>{label}</strong></span></button>; })}<div className="tree-status"><span className="status-badge">{workspace.publication ? workspace.publication.paused ? 'Paused · practice' : hasUnpublishedChanges ? 'Unpublished changes' : 'Published · practice' : 'Draft'}</span><p>One campaign, one ad set, one ad. Follow the setup and explain your decisions.</p></div><div className="tree-note">No real ad account is connected.</div></aside>
    <main className="workspace-main"><WorkspaceToolbar/>{storageError && <p className="storage-warning" role="alert">{storageError}</p>}<ProgressBar/><div className="editor-grid"><div id="step-main" className="settings-panel" tabIndex={-1}>{leftPanel}</div><aside className="preview-panel" aria-label="Ad preview"><div className="preview-sticky"><div className="preview-heading"><h2>Ad preview</h2><span className="status-badge neutral">Preview only</span></div>{rightPanel}<div className="preview-note"><InfoIcon contentKey="placements"/><p>Check the selected placement’s layout, image crop, copy, and destination.</p></div></div></aside></div><footer className="app-footer">Independent classroom practice tool. Your instructor evaluates the campaign. Publishing here does not run real ads.</footer></main></div>
  </div>;
}
